### ISSUE TITLE
插件安装失败

### ISSUE THREAD

**Issue by Superhero-zero** [hy0jer/HostScan#1]
![image](https://github.com/hy0jer/HostScan/assets/66772820/c0ce82d5-5347-45be-902e-6b4865d395ba)
测试了2020及2022版本的burp

**Comment by li-baige** [comment]
+1 我也报错
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1849)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1279)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:710)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:316)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:255)
	at burp.Zg5.Zv(Unknown Source)
	at burp.Zg5.Zy(Unknown Source)
	at burp.Zkqy.Zt(Unknown Source)
	at burp.Zosp.Zo(Unknown Source)
	at burp.Zzz8.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
2023版的Burp

**Comment by hy0jer** [comment]
> ![image](https://private-user-images.githubusercontent.com/66772820/307012014-c0ce82d5-5347-45be-902e-6b4865d395ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODA2OTAsIm5iZiI6MTcwODY4MDM5MCwicGF0aCI6Ii82Njc3MjgyMC8zMDcwMTIwMTQtYzBjZTgyZDUtNTM0Ny00NWJlLTkwMmUtNmI0ODY1ZDM5NWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA5MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMDAyZjUxODQ2ZTljNTRjZTIxZDQ2ZTk2MGVhMmIyMGQ1OTJkZWExYTlkMDExNmFlOTQ2ODUxZjM4Zjc3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VgM3IsHwO5-5Yn7toyFIABYVH39dz8Nci6RHlNHh0qo) 测试了2020及2022版本的burp

2022版本之前的burpsuite安装插件失败可能是由于不存在MontoyaApi，找不到该api所以安装失败，可以查看burp该页面确认是否存在该API
<img width="1090" alt="94bd746f192214ac9cb3c4bde064667" src="https://github.com/hy0jer/HostScan/assets/95990425/812a126d-4139-414a-9940-9c4be51e7b9e">

**Comment by hy0jer** [comment]
> +1 我也报错 at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) at java.base/java.nio.file.Files.readAttributes(Files.java:1849) at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1279) at java.base/java.util.zip.ZipFile$CleanableResource.(ZipFile.java:710) at java.base/java.util.zip.ZipFile.(ZipFile.java:243) at java.base/java.util.zip.ZipFile.(ZipFile.java:172) at java.base/java.util.jar.JarFile.(JarFile.java:345) at java.base/java.util.jar.JarFile.(JarFile.java:316) at java.base/java.util.jar.JarFile.(JarFile.java:255) at burp.Zg5.Zv(Unknown Source) at burp.Zg5.Zy(Unknown Source) at burp.Zkqy.Zt(Unknown Source) at burp.Zosp.Zo(Unknown Source) at burp.Zzz8.lambda$panelLoaded$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1589) 2023版的Burp

2023版本的burpsuite安装不上插件有可能是JDK环境问题，建议更换JDK版本为17.0.4以上再进行插件安装尝试

**Comment by hy0jer** [comment]
关于插件安装失败问题

我这里测试环境使用的JDK版本为jdk-17.0.4，burp suite版本为2023.2.2，插件安装失败，可能是由于JDK版本和burp版本问题，更换其他版本即可
<img width="728" alt="30bb1a9d4ba93b5852d0ea15dcfacd4" src="https://github.com/hy0jer/HostScan/assets/95990425/b5cb166d-97d8-48ca-ba1c-73742064ccbc">
